services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription-service
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user_subscription
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: d4fcfkbopklrmdfgflp2k3dfs1
    restart: on-failure

  db:
    image: postgres:15
    container_name: postgres-subscription
    environment:
      POSTGRES_DB: user_subscription
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: d4fcfkbopklrmdfgflp2k3dfs1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: